name: Acceptance
on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
jobs:
  acceptance:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      PIHOLE_URL: http://localhost:8080
      PIHOLE_API_TOKEN: 7b3d979ca8330a94fa7e9e1b466d8b99e0bcdea1ec90596c0dcc8d7ef6b4300c

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Start pihole
        run: docker-compose up -d

      - name: Run acceptance tests
        env:
          TEST_ACC: "1"
        run: go test -v ./...
